[package]
name = "app"
version = "0.1.0"
authors = ["David Barrat <david@barrat.io>"]
edition = "2018"
publish = false

[dependencies]
ssh2 = "0.9"
rocket = "0.4.7"

[[bin]]
name = "ssh-worker-build"
path = "src/main.rs"